### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by thomasburgess** [wptmdoorn/methcomp#19]
Note: travis is telling us: Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com - i guess we should think about migrating...

**Comment by wptmdoorn** [comment]
I will look into it, thanks :-) we most likely should

**Comment by thomasburgess** [comment]
I _think_ we could get away with using github actions for this: https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by thomasburgess** [comment]
I'd love to learn about this, perhaps I can give it a try later

**Comment by wptmdoorn** [comment]
I have migrated from travis-ci.org to travis-ci.com for now, as it would not check any new commits anymore. URL is:

**Comment by thomasburgess** [comment]
Awesome!

**Comment by wptmdoorn** [comment]
Is migrated.
