### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by thomasburgess** [wptmdoorn/methcomp#3]
Seems docs are offline at the moment...

**Comment by wptmdoorn** [comment]
Hi @thomasburgess, thank you for the remainder. I will fix it as soon as possible. In the meantime, can I help you with any questions?

**Comment by wptmdoorn** [comment]
> Hi @thomasburgess, thank you for the remainder. I will fix it as soon as possible. In the meantime, can I help you with any questions?

I updated the information and moved the documentation to readthedocs.io. I will close the issue for now, please let me know in case you want it re-opened if you have additional comments and/or questions. Again - thank you for the issue! :-)

**Comment by thomasburgess** [comment]
> > Hi @thomasburgess, thank you for the remainder. I will fix it as soon as possible. In the meantime, can I help you with any questions?
> 
> I updated the information and moved the documentation to readthedocs.io. I will close the issue for now, please let me know in case you want it re-opened if you have additional comments and/or questions. Again - thank you for the issue! :-)

Thanks for the software!
